/*
Sent.dm Core API

Testing WhatsappApiService

*/

// Code generated by Konfig (https://konfigthis.com);

package sentdm

import (
    "testing"
    // "github.com/stretchr/testify/assert"
    // "github.com/stretchr/testify/require"
    // sentdm "github.com/sentdm/sent-sdks/go"
)

func Test_sentdm_WhatsappApiService(t *testing.T) {

    // configuration := sentdm.NewConfiguration()
    // configuration.SetHost("http://127.0.0.1:4010")
    /* 
    configuration.SetApiKey("X_API_KEY")
    client := sentdm.NewAPIClient(configuration)
    */

    t.Run("Test WhatsappApiService GetWhatsappContact", func(t *testing.T) {
        /* TODO: ENG-1367 Fix parameter values for Go SDK generated tests
        request := client.WhatsappApi.GetWhatsappContact(
            ""+14155552671"",
            false,
        )
        request.SentId(""38400000-8cf0-11bd-b23e-10b96e4ef00d"")
        
        resp, httpRes, err := request.Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)
        */
    })

}