/**
 *
 * Please note:
 * This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dm.sent.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param error 
 * @param details 
 */

data class MessagesSendMessageToContact400Response (

    @Json(name = "error")
    val error: kotlin.String? = null,

    @Json(name = "details")
    val details: kotlin.collections.List<kotlin.String>? = null

)

