/**
 *
 * Please note:
 * This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dm.sent.client.models


import com.squareup.moshi.Json

/**
 * Basic phone number payload information
 *
 * @param id Unique identifier for the phone number record
 * @param sentId Sent platform identifier
 * @param phoneNumber Phone number in E.164 format
 */

data class PayloadPhoneNumber (

    /* Unique identifier for the phone number record */
    @Json(name = "id")
    val id: java.util.UUID? = null,

    /* Sent platform identifier */
    @Json(name = "sentId")
    val sentId: java.util.UUID? = null,

    /* Phone number in E.164 format */
    @Json(name = "phoneNumber")
    val phoneNumber: kotlin.String? = null

)

