/**
 *
 * Please note:
 * This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dm.sent.client.models


import com.squareup.moshi.Json

/**
 * Request model for creating a new message template
 *
 * @param customerId Unique identifier of the customer creating the template
 * @param name Name of the template for identification purposes
 */

data class TemplateCreateRequest (

    /* Unique identifier of the customer creating the template */
    @Json(name = "customerId")
    val customerId: java.util.UUID,

    /* Name of the template for identification purposes */
    @Json(name = "name")
    val name: kotlin.String

)

