/**
 *
 * Please note:
 * This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dm.sent.client.models


import com.squareup.moshi.Json

/**
 * 
 *
 * @param whatsappId Unique WhatsApp identifier for the contact
 * @param countryCode ISO country code of the phone number
 * @param numberType Type of phone number (MOBILE, LANDLINE, etc)
 * @param profilePicture URL to the contact's WhatsApp profile picture
 * @param isBusiness Indicates if the number belongs to a WhatsApp Business account
 * @param invalidRecord Indicates if the WhatsApp account is invalid or deactivated
 */

data class WhatsAppPayloadAllOf (

    /* Unique WhatsApp identifier for the contact */
    @Json(name = "whatsappId")
    val whatsappId: kotlin.String? = null,

    /* ISO country code of the phone number */
    @Json(name = "countryCode")
    val countryCode: kotlin.String? = null,

    /* Type of phone number (MOBILE, LANDLINE, etc) */
    @Json(name = "numberType")
    val numberType: WhatsAppPayloadAllOf.NumberType? = null,

    /* URL to the contact's WhatsApp profile picture */
    @Json(name = "profilePicture")
    val profilePicture: kotlin.String? = null,

    /* Indicates if the number belongs to a WhatsApp Business account */
    @Json(name = "isBusiness")
    val isBusiness: kotlin.Boolean? = null,

    /* Indicates if the WhatsApp account is invalid or deactivated */
    @Json(name = "invalidRecord")
    val invalidRecord: kotlin.Boolean? = null

) {

    /**
     * Type of phone number (MOBILE, LANDLINE, etc)
     *
     * Values: mOBILE,lANDLINE,vOIP,uNKNOWN
     */
    enum class NumberType(val value: kotlin.String) {
        @Json(name = "MOBILE") mOBILE("MOBILE"),
        @Json(name = "LANDLINE") lANDLINE("LANDLINE"),
        @Json(name = "VOIP") vOIP("VOIP"),
        @Json(name = "UNKNOWN") uNKNOWN("UNKNOWN");
    }
}

