/*
Sent.dm Core API

Sent.dm is a unified messaging API that enables developers to seamlessly send messages across multiple channels including SMS and WhatsApp. It provides programmatic management of customer accounts, messaging capabilities with intelligent routing, message delivery, and template management. The API supports creating, updating, and managing customer profiles, sending messages using templates, retrieving contact information, and handling templates across different messaging channels.

The version of the OpenAPI document: 1.1.0
Contact: developers@sent.dm

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Basic phone number payload information
 * @export
 * @interface PayloadPhoneNumber
 */
export interface PayloadPhoneNumber {
    /**
     * Unique identifier for the phone number record
     * @type {string}
     * @memberof PayloadPhoneNumber
     */
    'id'?: string;
    /**
     * Sent platform identifier
     * @type {string}
     * @memberof PayloadPhoneNumber
     */
    'sentId'?: string;
    /**
     * Phone number in E.164 format
     * @type {string}
     * @memberof PayloadPhoneNumber
     */
    'phoneNumber'?: string;
}

