/*
Sent.dm Core API

Sent.dm is a unified messaging API that enables developers to seamlessly send messages across multiple channels including SMS and WhatsApp. It provides programmatic management of customer accounts, messaging capabilities with intelligent routing, message delivery, and template management. The API supports creating, updating, and managing customer profiles, sending messages using templates, retrieving contact information, and handling templates across different messaging channels.

API version: 1.1.0
Contact: developers@sent.dm
*/

// Code generated by Konfig (https://konfigthis.com); DO NOT EDIT.

package sentdm

import (
	"encoding/json"
)

// CustomersUpdateCustomerRequest Request model for updating customer information
type CustomersUpdateCustomerRequest struct {
	// Updated name of the customer organization
	Name *string `json:"name,omitempty"`
	// Updated primary phone number for sending messages
	SendingPhoneNumber *string `json:"sendingPhoneNumber,omitempty"`
	// Updated SMS messaging profile identifier
	SmsMessagingProfileId *string `json:"smsMessagingProfileId,omitempty"`
	// Updated bearer token for SMS authentication
	SmsBearerToken *string `json:"smsBearerToken,omitempty"`
}

// NewCustomersUpdateCustomerRequest instantiates a new CustomersUpdateCustomerRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomersUpdateCustomerRequest() *CustomersUpdateCustomerRequest {
	this := CustomersUpdateCustomerRequest{}
	return &this
}

// NewCustomersUpdateCustomerRequestWithDefaults instantiates a new CustomersUpdateCustomerRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomersUpdateCustomerRequestWithDefaults() *CustomersUpdateCustomerRequest {
	this := CustomersUpdateCustomerRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CustomersUpdateCustomerRequest) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomersUpdateCustomerRequest) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
    return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CustomersUpdateCustomerRequest) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CustomersUpdateCustomerRequest) SetName(v string) {
	o.Name = &v
}

// GetSendingPhoneNumber returns the SendingPhoneNumber field value if set, zero value otherwise.
func (o *CustomersUpdateCustomerRequest) GetSendingPhoneNumber() string {
	if o == nil || isNil(o.SendingPhoneNumber) {
		var ret string
		return ret
	}
	return *o.SendingPhoneNumber
}

// GetSendingPhoneNumberOk returns a tuple with the SendingPhoneNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomersUpdateCustomerRequest) GetSendingPhoneNumberOk() (*string, bool) {
	if o == nil || isNil(o.SendingPhoneNumber) {
    return nil, false
	}
	return o.SendingPhoneNumber, true
}

// HasSendingPhoneNumber returns a boolean if a field has been set.
func (o *CustomersUpdateCustomerRequest) HasSendingPhoneNumber() bool {
	if o != nil && !isNil(o.SendingPhoneNumber) {
		return true
	}

	return false
}

// SetSendingPhoneNumber gets a reference to the given string and assigns it to the SendingPhoneNumber field.
func (o *CustomersUpdateCustomerRequest) SetSendingPhoneNumber(v string) {
	o.SendingPhoneNumber = &v
}

// GetSmsMessagingProfileId returns the SmsMessagingProfileId field value if set, zero value otherwise.
func (o *CustomersUpdateCustomerRequest) GetSmsMessagingProfileId() string {
	if o == nil || isNil(o.SmsMessagingProfileId) {
		var ret string
		return ret
	}
	return *o.SmsMessagingProfileId
}

// GetSmsMessagingProfileIdOk returns a tuple with the SmsMessagingProfileId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomersUpdateCustomerRequest) GetSmsMessagingProfileIdOk() (*string, bool) {
	if o == nil || isNil(o.SmsMessagingProfileId) {
    return nil, false
	}
	return o.SmsMessagingProfileId, true
}

// HasSmsMessagingProfileId returns a boolean if a field has been set.
func (o *CustomersUpdateCustomerRequest) HasSmsMessagingProfileId() bool {
	if o != nil && !isNil(o.SmsMessagingProfileId) {
		return true
	}

	return false
}

// SetSmsMessagingProfileId gets a reference to the given string and assigns it to the SmsMessagingProfileId field.
func (o *CustomersUpdateCustomerRequest) SetSmsMessagingProfileId(v string) {
	o.SmsMessagingProfileId = &v
}

// GetSmsBearerToken returns the SmsBearerToken field value if set, zero value otherwise.
func (o *CustomersUpdateCustomerRequest) GetSmsBearerToken() string {
	if o == nil || isNil(o.SmsBearerToken) {
		var ret string
		return ret
	}
	return *o.SmsBearerToken
}

// GetSmsBearerTokenOk returns a tuple with the SmsBearerToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomersUpdateCustomerRequest) GetSmsBearerTokenOk() (*string, bool) {
	if o == nil || isNil(o.SmsBearerToken) {
    return nil, false
	}
	return o.SmsBearerToken, true
}

// HasSmsBearerToken returns a boolean if a field has been set.
func (o *CustomersUpdateCustomerRequest) HasSmsBearerToken() bool {
	if o != nil && !isNil(o.SmsBearerToken) {
		return true
	}

	return false
}

// SetSmsBearerToken gets a reference to the given string and assigns it to the SmsBearerToken field.
func (o *CustomersUpdateCustomerRequest) SetSmsBearerToken(v string) {
	o.SmsBearerToken = &v
}

func (o CustomersUpdateCustomerRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !isNil(o.SendingPhoneNumber) {
		toSerialize["sendingPhoneNumber"] = o.SendingPhoneNumber
	}
	if !isNil(o.SmsMessagingProfileId) {
		toSerialize["smsMessagingProfileId"] = o.SmsMessagingProfileId
	}
	if !isNil(o.SmsBearerToken) {
		toSerialize["smsBearerToken"] = o.SmsBearerToken
	}
	return json.Marshal(toSerialize)
}

type NullableCustomersUpdateCustomerRequest struct {
	value *CustomersUpdateCustomerRequest
	isSet bool
}

func (v NullableCustomersUpdateCustomerRequest) Get() *CustomersUpdateCustomerRequest {
	return v.value
}

func (v *NullableCustomersUpdateCustomerRequest) Set(val *CustomersUpdateCustomerRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomersUpdateCustomerRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomersUpdateCustomerRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomersUpdateCustomerRequest(val *CustomersUpdateCustomerRequest) *NullableCustomersUpdateCustomerRequest {
	return &NullableCustomersUpdateCustomerRequest{value: val, isSet: true}
}

func (v NullableCustomersUpdateCustomerRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomersUpdateCustomerRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


