//
// MessagesSendMessageToPhoneNumberResponse.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MessagesSendMessageToPhoneNumberResponse: Codable, JSONEncodable, Hashable {

    public enum Status: String, Codable, CaseIterable {
        case queued = "queued"
        case sending = "sending"
        case delivered = "delivered"
    }
    public enum Channel: String, Codable, CaseIterable {
        case sms = "sms"
        case whatsapp = "whatsapp"
    }
    public var messageId: String?
    public var status: Status?
    public var channel: Channel?
    /** ID of the created or existing contact */
    public var contactId: String?

    public init(messageId: String? = nil, status: Status? = nil, channel: Channel? = nil, contactId: String? = nil) {
        self.messageId = messageId
        self.status = status
        self.channel = channel
        self.contactId = contactId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case messageId
        case status
        case channel
        case contactId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var codingContainer = encoder.container(keyedBy: CodingKeys.self)
        try codingContainer.encodeIfPresent(messageId, forKey: .messageId)
        try codingContainer.encodeIfPresent(status, forKey: .status)
        try codingContainer.encodeIfPresent(channel, forKey: .channel)
        try codingContainer.encodeIfPresent(contactId, forKey: .contactId)
    }
}

