//
// PayloadPhoneNumber.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Basic phone number payload information */
public struct PayloadPhoneNumber: Codable, JSONEncodable, Hashable {

    /** Unique identifier for the phone number record */
    public var id: String?
    /** Sent platform identifier */
    public var sentId: String?
    /** Phone number in E.164 format */
    public var phoneNumber: String?

    public init(id: String? = nil, sentId: String? = nil, phoneNumber: String? = nil) {
        self.id = id
        self.sentId = sentId
        self.phoneNumber = phoneNumber
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case sentId
        case phoneNumber
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var codingContainer = encoder.container(keyedBy: CodingKeys.self)
        try codingContainer.encodeIfPresent(id, forKey: .id)
        try codingContainer.encodeIfPresent(sentId, forKey: .sentId)
        try codingContainer.encodeIfPresent(phoneNumber, forKey: .phoneNumber)
    }
}

