/*
 * Sent.dm Core API
 *
 * Sent.dm is a unified messaging API that enables developers to seamlessly send messages across multiple channels including SMS and WhatsApp. It provides programmatic management of customer accounts, messaging capabilities with intelligent routing, message delivery, and template management. The API supports creating, updating, and managing customer profiles, sending messages using templates, retrieving contact information, and handling templates across different messaging channels.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: developers@sent.dm
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sentdm.Net.Api;
using Sentdm.Net.Model;
using Sentdm.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Sentdm.Net.Test.Model
{
    /// <summary>
    ///  Class for testing MessagesSendMessageToContact400Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MessagesSendMessageToContact400ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MessagesSendMessageToContact400Response
        //private MessagesSendMessageToContact400Response instance;

        public MessagesSendMessageToContact400ResponseTests()
        {
            // TODO uncomment below to create an instance of MessagesSendMessageToContact400Response
            //instance = new MessagesSendMessageToContact400Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MessagesSendMessageToContact400Response
        /// </summary>
        [Fact]
        public void MessagesSendMessageToContact400ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" MessagesSendMessageToContact400Response
            //Assert.IsType<MessagesSendMessageToContact400Response>(instance);
        }


        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }
        /// <summary>
        /// Test the property 'Details'
        /// </summary>
        [Fact]
        public void DetailsTest()
        {
            // TODO unit test for the property 'Details'
        }

    }

}
