# coding: utf-8

"""
    Sent.dm Core API

    Sent.dm is a unified messaging API that enables developers to seamlessly send messages across multiple channels including SMS and WhatsApp. It provides programmatic management of customer accounts, messaging capabilities with intelligent routing, message delivery, and template management. The API supports creating, updating, and managing customer profiles, sending messages using templates, retrieving contact information, and handling templates across different messaging channels.

    The version of the OpenAPI document: 1.1.0
    Contact: developers@sent.dm
    Created by: https://www.sent.dm/
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from sentdm import schemas  # noqa: F401


class CustomersUpdateCustomerRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Request model for updating customer information
    """


    class MetaOapg:
        
        class properties:
            name = schemas.StrSchema
            sendingPhoneNumber = schemas.StrSchema
            smsMessagingProfileId = schemas.StrSchema
            smsBearerToken = schemas.StrSchema
            __annotations__ = {
                "name": name,
                "sendingPhoneNumber": sendingPhoneNumber,
                "smsMessagingProfileId": smsMessagingProfileId,
                "smsBearerToken": smsBearerToken,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["sendingPhoneNumber"]) -> MetaOapg.properties.sendingPhoneNumber: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["smsMessagingProfileId"]) -> MetaOapg.properties.smsMessagingProfileId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["smsBearerToken"]) -> MetaOapg.properties.smsBearerToken: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["name", "sendingPhoneNumber", "smsMessagingProfileId", "smsBearerToken", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> typing.Union[MetaOapg.properties.name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["sendingPhoneNumber"]) -> typing.Union[MetaOapg.properties.sendingPhoneNumber, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["smsMessagingProfileId"]) -> typing.Union[MetaOapg.properties.smsMessagingProfileId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["smsBearerToken"]) -> typing.Union[MetaOapg.properties.smsBearerToken, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["name", "sendingPhoneNumber", "smsMessagingProfileId", "smsBearerToken", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        name: typing.Union[MetaOapg.properties.name, str, schemas.Unset] = schemas.unset,
        sendingPhoneNumber: typing.Union[MetaOapg.properties.sendingPhoneNumber, str, schemas.Unset] = schemas.unset,
        smsMessagingProfileId: typing.Union[MetaOapg.properties.smsMessagingProfileId, str, schemas.Unset] = schemas.unset,
        smsBearerToken: typing.Union[MetaOapg.properties.smsBearerToken, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'CustomersUpdateCustomerRequest':
        return super().__new__(
            cls,
            *args,
            name=name,
            sendingPhoneNumber=sendingPhoneNumber,
            smsMessagingProfileId=smsMessagingProfileId,
            smsBearerToken=smsBearerToken,
            _configuration=_configuration,
            **kwargs,
        )
